export const indexDatas = [{
    "INDEXID": "A",
    "INDEXNAME": "藏品信息指标群",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "ABC",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c16216563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A01",
    "INDEXNAME": "名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1664d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0101",
    "INDEXNAME": "学术定名",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 400,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c16765563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0102",
    "INDEXNAME": "大账名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1685a563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0103",
    "INDEXNAME": "曾用名",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c16947563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A02",
    "INDEXNAME": "类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c16a28563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0201",
    "INDEXNAME": "藏品基本部类",
    "IDATATYPE": "1",
    "ISELTYPE": "cpjbbl",
    "ENDFLAG": "1",
    "SUPERID": "A02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 10,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c16b12563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0211",
    "INDEXNAME": "藏品类别",
    "IDATATYPE": "1",
    "ISELTYPE": "wwlb",
    "ENDFLAG": "1",
    "SUPERID": "A02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c16bff563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0212",
    "INDEXNAME": "标本类别",
    "IDATATYPE": "1",
    "ISELTYPE": "bzlb",
    "ENDFLAG": "1",
    "SUPERID": "A02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c16dad563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0213",
    "INDEXNAME": "模型类别",
    "IDATATYPE": "1",
    "ISELTYPE": "mxlb",
    "ENDFLAG": "1",
    "SUPERID": "A02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c16f68563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0214",
    "INDEXNAME": "复制品类别",
    "IDATATYPE": "1",
    "ISELTYPE": "fzplb",
    "ENDFLAG": "1",
    "SUPERID": "A02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c17343563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A03",
    "INDEXNAME": "年代",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1742c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0301",
    "INDEXNAME": "年代类型",
    "IDATATYPE": "1",
    "ISELTYPE": "ndlx",
    "ENDFLAG": "1",
    "SUPERID": "A03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c174fe563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0302",
    "INDEXNAME": "年代表示方式",
    "IDATATYPE": "1",
    "ISELTYPE": "ndbsfs",
    "ENDFLAG": "1",
    "SUPERID": "A03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c175db563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0310",
    "INDEXNAME": "年代",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 4000,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c176bc563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0311",
    "INDEXNAME": "年代编号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 10,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c177a1563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A04",
    "INDEXNAME": "地域",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c17877563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0401",
    "INDEXNAME": "地域类型",
    "IDATATYPE": "1",
    "ISELTYPE": "dylx",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c17954563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0402",
    "INDEXNAME": "地域表示方式",
    "IDATATYPE": "1",
    "ISELTYPE": "dybsfs",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c17a51563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0410",
    "INDEXNAME": "地域",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c17b32563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0421",
    "INDEXNAME": "制造地",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c17c07563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0422",
    "INDEXNAME": "使用地",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c17ce4563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0423",
    "INDEXNAME": "出土地",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c17dca563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0424",
    "INDEXNAME": "采集地",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c17ec6563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A05",
    "INDEXNAME": "人文",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18075563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0501",
    "INDEXNAME": "人文类型",
    "IDATATYPE": "1",
    "ISELTYPE": "rwlb",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "12",
    "remark": "",
    "id": "88c18156563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0502",
    "INDEXNAME": "人文表示方式",
    "IDATATYPE": "1",
    "ISELTYPE": "rwbsfs",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1823f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0510",
    "INDEXNAME": "人文",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c18334563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0521",
    "INDEXNAME": "制造者",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18441563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0522",
    "INDEXNAME": "仿制者",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1852e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0523",
    "INDEXNAME": "使用者",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c186d1563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0524",
    "INDEXNAME": "属有者",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c187b2563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0540",
    "INDEXNAME": "人物传略",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18883563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A06",
    "INDEXNAME": "质地",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18959563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0601",
    "INDEXNAME": "质地类别",
    "IDATATYPE": "1",
    "ISELTYPE": "zdlb",
    "ENDFLAG": "1",
    "SUPERID": "A06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c18a36563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0602",
    "INDEXNAME": "质地子类别",
    "IDATATYPE": "1",
    "ISELTYPE": "zdzlb",
    "ENDFLAG": "1",
    "SUPERID": "A06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18b0f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0610",
    "INDEXNAME": "质地",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18be8563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A07",
    "INDEXNAME": "功能",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18cbe563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0702",
    "INDEXNAME": "功能类别",
    "IDATATYPE": "1",
    "ISELTYPE": "gnlb",
    "ENDFLAG": "1",
    "SUPERID": "A07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18d9f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0710",
    "INDEXNAME": "功能",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c18e78563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0711",
    "INDEXNAME": "实际用途",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c18f4e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A08",
    "INDEXNAME": "工艺技法",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19027563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0801",
    "INDEXNAME": "成型工艺",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c19104563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0810",
    "INDEXNAME": "流派类型",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c191d9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0811",
    "INDEXNAME": "流派",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c192b7563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0812",
    "INDEXNAME": "绘画技法",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19394563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0821",
    "INDEXNAME": "装饰生成工艺",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 30,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1960c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0822",
    "INDEXNAME": "文字生成工艺",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 30,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c196e9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A09",
    "INDEXNAME": "形态",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c197b7563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0901",
    "INDEXNAME": "物态类别",
    "IDATATYPE": "1",
    "ISELTYPE": "wtlb",
    "ENDFLAG": "1",
    "SUPERID": "A09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19894563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0911",
    "INDEXNAME": "形态特征",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19a43563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A0912",
    "INDEXNAME": "独特标记",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19b24563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A10",
    "INDEXNAME": "完残",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19bfd563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1001",
    "INDEXNAME": "完残程度",
    "IDATATYPE": "1",
    "ISELTYPE": "wccd",
    "ENDFLAG": "1",
    "SUPERID": "A10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c19cd6563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1011",
    "INDEXNAME": "完残状况",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c19e71563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1021",
    "INDEXNAME": "新残情况",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c19f3f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A11",
    "INDEXNAME": "色泽",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1a010563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1101",
    "INDEXNAME": "颜色类别",
    "IDATATYPE": "1",
    "ISELTYPE": "yslb",
    "ENDFLAG": "1",
    "SUPERID": "A11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1a0e5563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1102",
    "INDEXNAME": "光泽类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1a1c6563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1120",
    "INDEXNAME": "光泽",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1a29c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1121",
    "INDEXNAME": "颜色",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1a375563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A12",
    "INDEXNAME": "装饰",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1a44e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1201",
    "INDEXNAME": "装饰形式类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A12",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1a52c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1202",
    "INDEXNAME": "装饰题材类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A12",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1a609563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1203",
    "INDEXNAME": "装饰组合方式",
    "IDATATYPE": "1",
    "ISELTYPE": "zszhfs",
    "ENDFLAG": "1",
    "SUPERID": "A12",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1a6da563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1204",
    "INDEXNAME": "施饰部位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A12",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1a8b4563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A13",
    "INDEXNAME": "题识内容",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1aa6b563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1301",
    "INDEXNAME": "铭文",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A13",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1ab44563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1302",
    "INDEXNAME": "款识",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A13",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1ac15563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1303",
    "INDEXNAME": "题跋",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A13",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 300,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1acf3563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1304",
    "INDEXNAME": "题名",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A13",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 300,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1add8563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1305",
    "INDEXNAME": "印鉴",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A13",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 300,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1aebd563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1306",
    "INDEXNAME": "内容提要",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A13",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1af92563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A14",
    "INDEXNAME": "文字",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b070563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1401",
    "INDEXNAME": "文字种类",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A14",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1b14d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1402",
    "INDEXNAME": "字体类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A14",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1b22e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1403",
    "INDEXNAME": "字迹颜色",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A14",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1b307563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1410",
    "INDEXNAME": "字体",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A14",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b3ec563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A15",
    "INDEXNAME": "自然特征",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b4ca563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1501",
    "INDEXNAME": "化石类别",
    "IDATATYPE": "1",
    "ISELTYPE": "hslb",
    "ENDFLAG": "1",
    "SUPERID": "A15",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c1b5a3563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1502",
    "INDEXNAME": "模式类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A15",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b670563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1503",
    "INDEXNAME": "发育阶段",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A15",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b74e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1504",
    "INDEXNAME": "性别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A15",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b843563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1510",
    "INDEXNAME": "化石",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A15",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b91c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A16",
    "INDEXNAME": "计量",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1b9ed563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1611",
    "INDEXNAME": "尺寸",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A16",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c1baca563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1612",
    "INDEXNAME": "尺寸单位",
    "IDATATYPE": "1",
    "ISELTYPE": "cddw",
    "ENDFLAG": "1",
    "SUPERID": "A16",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2dce6563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1621",
    "INDEXNAME": "容积",
    "IDATATYPE": "4",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A16",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2de99563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1622",
    "INDEXNAME": "容积单位",
    "IDATATYPE": "1",
    "ISELTYPE": "rjdw",
    "ENDFLAG": "1",
    "SUPERID": "A16",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2df9d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1631",
    "INDEXNAME": "质量",
    "IDATATYPE": "4",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A16",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e09a563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1632",
    "INDEXNAME": "质量单位",
    "IDATATYPE": "1",
    "ISELTYPE": "zldw",
    "ENDFLAG": "1",
    "SUPERID": "A16",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e193563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A17",
    "INDEXNAME": "计数",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2e27c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1701",
    "INDEXNAME": "件数",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A17",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e365563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1702",
    "INDEXNAME": "实际数量单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A17",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e45a563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1711",
    "INDEXNAME": "件套数",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A17",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e54f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1712",
    "INDEXNAME": "传统数量单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A17",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e644563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A18",
    "INDEXNAME": "附件",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2e725563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1801",
    "INDEXNAME": "附件名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A18",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2e806563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1821",
    "INDEXNAME": "附件现状",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A18",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2ea4b563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1831",
    "INDEXNAME": "附件数量",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A18",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2eb30563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1832",
    "INDEXNAME": "附件数量单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A18",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2ec12563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A19",
    "INDEXNAME": "附属物",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2ecf7563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1901",
    "INDEXNAME": "附属物名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A19",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2ede0563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1921",
    "INDEXNAME": "附属物现状",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A19",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2eec9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1931",
    "INDEXNAME": "附属物数量",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A19",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2efd9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A1932",
    "INDEXNAME": "附属物数量单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A19",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2f0d2563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A20",
    "INDEXNAME": "备注",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f1d3563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A2001",
    "INDEXNAME": "备注",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A20",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c2f2cc563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A2002",
    "INDEXNAME": "图片",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A20",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c2f3ad563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A22",
    "INDEXNAME": "属性",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "A",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f48a563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A2201",
    "INDEXNAME": "国别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A22",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f568563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A2202",
    "INDEXNAME": "民族",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A22",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f641563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "A2209",
    "INDEXNAME": "器物描述",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "A22",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f716563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "ABC",
    "INDEXNAME": "馆藏指标体系",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "GB",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f7f4563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B",
    "INDEXNAME": "藏品管理工作信息",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "ABC",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f8d1563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B01",
    "INDEXNAME": "搜集",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2f9aa563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0101",
    "INDEXNAME": "来源",
    "IDATATYPE": "1",
    "ISELTYPE": "wwly",
    "ENDFLAG": "1",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2fa83563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0102",
    "INDEXNAME": "来源单位或个人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2fb70563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0103",
    "INDEXNAME": "来源号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2fc5d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0104",
    "INDEXNAME": "搜集经过",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 4000,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c2fd43563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0107",
    "INDEXNAME": "来源日期",
    "IDATATYPE": "3",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c2fe1c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0111",
    "INDEXNAME": "申请搜集经费",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c2ff01563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0112",
    "INDEXNAME": "实际搜集经费",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c2ffea563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0121",
    "INDEXNAME": "流传经历",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 4000,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c300cb563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B02",
    "INDEXNAME": "入馆",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c301a8563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0201",
    "INDEXNAME": "收藏单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30292563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0211",
    "INDEXNAME": "入馆登记号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3038a563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0212",
    "INDEXNAME": "入馆日期",
    "IDATATYPE": "3",
    "ISELTYPE": "",
    "ENDFLAG": "",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c30474563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0213",
    "INDEXNAME": "总登记号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c30561563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0214",
    "INDEXNAME": "入藏日期",
    "IDATATYPE": "3",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c30646563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0215",
    "INDEXNAME": "入藏库房",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30737563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0216",
    "INDEXNAME": "存放方位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c30820563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0217",
    "INDEXNAME": "分类号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c308f9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0251",
    "INDEXNAME": "分类单号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c309da563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0252",
    "INDEXNAME": "拓片号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30ac3563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0253",
    "INDEXNAME": "底版号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30ba5563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0254",
    "INDEXNAME": "入馆凭证号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30c7e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0255",
    "INDEXNAME": "注销凭证号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30d63563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0256",
    "INDEXNAME": "价格",
    "IDATATYPE": "4",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30e58563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0257",
    "INDEXNAME": "备注",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 4000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c30f4d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0258",
    "INDEXNAME": "经手人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 40,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3102e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B03",
    "INDEXNAME": "鉴定",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c31113563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0301",
    "INDEXNAME": "鉴定日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c311fc563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0302",
    "INDEXNAME": "鉴定机构",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c312e1563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0303",
    "INDEXNAME": "鉴定人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c313c3563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0304",
    "INDEXNAME": "鉴定意见",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c314a8563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B04",
    "INDEXNAME": "定级",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c315a5563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0401",
    "INDEXNAME": "藏品级别",
    "IDATATYPE": "1",
    "ISELTYPE": "cpjb",
    "ENDFLAG": "1",
    "SUPERID": "B04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c3168e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0402",
    "INDEXNAME": "文物藏品保密级别",
    "IDATATYPE": "1",
    "ISELTYPE": "bmjb",
    "ENDFLAG": "1",
    "SUPERID": "B04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3176b563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0403",
    "INDEXNAME": "标本藏品级别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B04",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c31858563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B05",
    "INDEXNAME": "现状",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c31951563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0501",
    "INDEXNAME": "当前状况",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c31a32563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0502",
    "INDEXNAME": "当前处所",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c31b0b563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0503",
    "INDEXNAME": "当前保存条件",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c31bf4563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0511",
    "INDEXNAME": "自然损坏",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c31ced563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0512",
    "INDEXNAME": "人为损坏",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B05",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c31dd2563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B06",
    "INDEXNAME": "保护",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c31eac563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0601",
    "INDEXNAME": "保护优先等级",
    "IDATATYPE": "1",
    "ISELTYPE": "bhyxdj",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 20,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c31f91563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0602",
    "INDEXNAME": "当前处所",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 100,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3207e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0611",
    "INDEXNAME": "保护措施",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32163563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0621",
    "INDEXNAME": "保护技术类别",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c3223c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0630",
    "INDEXNAME": "保护记录",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32329563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0641",
    "INDEXNAME": "保护经费预算",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c32412563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0642",
    "INDEXNAME": "保护经费结算",
    "IDATATYPE": "2",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B06",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 12,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c324f0563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B07",
    "INDEXNAME": "提取",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c325d1563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0701",
    "INDEXNAME": "提取日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c326b2563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0702",
    "INDEXNAME": "提取原因",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c327a7563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0703",
    "INDEXNAME": "提取登记号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32890563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0704",
    "INDEXNAME": "提取单位或部门",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32981563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0705",
    "INDEXNAME": "提取负责人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32a92563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0706",
    "INDEXNAME": "提取人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32b9e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0707",
    "INDEXNAME": "审批单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32c93563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0708",
    "INDEXNAME": "审批人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "1",
    "BREVIARY": "",
    "remark": "1",
    "id": "88c32d94563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0709",
    "INDEXNAME": "批准文号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c32e9d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0710",
    "INDEXNAME": "报保管部负责人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3309e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0711",
    "INDEXNAME": "出库点交人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c331a7563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0712",
    "INDEXNAME": "出库验交记录",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B07",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3328c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B08",
    "INDEXNAME": "退还",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33375563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0801",
    "INDEXNAME": "退还日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3345e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0802",
    "INDEXNAME": "退还人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33543563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0803",
    "INDEXNAME": "回库点收人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33628563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0804",
    "INDEXNAME": "回库点交记录",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B08",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33712563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B09",
    "INDEXNAME": "事故",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33803563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0901",
    "INDEXNAME": "事故发生日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c338f4563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0902",
    "INDEXNAME": "事故经过",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c339d9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0903",
    "INDEXNAME": "事故责任人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33ac2563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0904",
    "INDEXNAME": "藏品损失情况",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 200,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33bb3563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B0905",
    "INDEXNAME": "事故处理结果",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B09",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 1000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c33c98563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B10",
    "INDEXNAME": "注销",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c37728563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1001",
    "INDEXNAME": "注销原因",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 500,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c37874563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1002",
    "INDEXNAME": "注销日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c37979563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1003",
    "INDEXNAME": "注销批准文号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c37a72563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1004",
    "INDEXNAME": "注销审批人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c37b5f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1005",
    "INDEXNAME": "注销后去向",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B10",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 300,
    "dataformat": "",
    "BREVIARY": "1",
    "remark": "",
    "id": "88c37c54563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B11",
    "INDEXNAME": "统计",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "B",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c37d49563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1101",
    "INDEXNAME": "统计表名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c37e3e563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1102",
    "INDEXNAME": "统计资料起止时间",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c37f2b563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1103",
    "INDEXNAME": "统计单位",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c38020563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1104",
    "INDEXNAME": "统计人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38101563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "B1105",
    "INDEXNAME": "统计日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "B11",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c381f2563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C",
    "INDEXNAME": "藏品文档信息、研究论著信息与声像资料信息",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "ABC",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c382d7563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C01",
    "INDEXNAME": "管理文档",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "C",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38547563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0101",
    "INDEXNAME": "文档名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3867f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0102",
    "INDEXNAME": "文档编号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3876c563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0103",
    "INDEXNAME": "文档类型",
    "IDATATYPE": "1",
    "ISELTYPE": "wdlx",
    "ENDFLAG": "1",
    "SUPERID": "C01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3884a563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0104",
    "INDEXNAME": "制档日期",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3893f563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0105",
    "INDEXNAME": "制档人",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C01",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38a20563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C02",
    "INDEXNAME": "研究论著",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "C",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38b0d563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0201",
    "INDEXNAME": "研究论著题名",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "",
    "SUPERID": "C02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": "",
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38bea563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0211",
    "INDEXNAME": "研究论著类型",
    "IDATATYPE": "1",
    "ISELTYPE": "yjlzlx",
    "ENDFLAG": "1",
    "SUPERID": "C02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "0",
    "remark": "",
    "id": "88c38ccf563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0220",
    "INDEXNAME": "研究论著情况",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 4000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38db8563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0221",
    "INDEXNAME": "研究论著详细内容",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C02",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 4000,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38ea9563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C03",
    "INDEXNAME": "声像资料",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "0",
    "SUPERID": "C",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 0,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c38f87563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0301",
    "INDEXNAME": "声像资料名称",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c39058563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0302",
    "INDEXNAME": "声像资料编号",
    "IDATATYPE": "1",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c39141563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0311",
    "INDEXNAME": "声像资料类别",
    "IDATATYPE": "1",
    "ISELTYPE": "sxztlb",
    "ENDFLAG": "1",
    "SUPERID": "C03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "0",
    "ISRequired": "0",
    "INDEXWIDTH": 50,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c39226563611e6a87100acc7b0340c"
  },
  {
    "INDEXID": "C0320",
    "INDEXNAME": "声像资料情况",
    "IDATATYPE": "5",
    "ISELTYPE": "",
    "ENDFLAG": "1",
    "SUPERID": "C03",
    "SORTID": "",
    "Is_Single_Level": "",
    "ISCORE": "1",
    "ISRequired": "0",
    "INDEXWIDTH": 500,
    "dataformat": "",
    "BREVIARY": "",
    "remark": "",
    "id": "88c3931b563611e6a87100acc7b0340c"
  }
]

export const indexTreeDatas = [{
    id: "A",
    label: "藏品信息指标集",
    children: [{
      id: "A01",
      label: "名称"

    }, {
      id: "A02",
      label: "类别"
    }]
  },
  {
    id: "B",
    label: "藏品管理工作信息",
    children: [{
      id: "B01",
      label: "搜集"

    }, {
      id: "B02",
      label: "入馆"

    }]
  }, {
    id: "C",
    label: "藏品文档信息、研究论著信息与声像资料信息",
    children: [{
      id: "C01",
      label: "管理文档"

    }, {
      id: "C02",
      label: "研究论著"

    }]
  }


]


export const dataTypes = [{
    value: "1",
    label: "字符"
  },
  {
    value: "2",
    label: "数字"
  },
  {
    value: "3",
    label: "日期"
  },
  {
    value: "4",
    label: "小数"
  },
  {
    value: "5",
    label: "大文本"
  }
]
